"""Added Role

Revision ID: 0825f7a20c85
Revises: a55c20d6f9fb
Create Date: 2020-03-19 18:23:26.176013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0825f7a20c85'
down_revision = 'a55c20d6f9fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users._id'], )
    )
    op.add_column('Users', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('Users', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'confirmed_at')
    op.drop_column('Users', 'active')
    op.drop_table('roles_users')
    # ### end Alembic commands ###
