"""Deleted Role

Revision ID: fd359ff9cd8a
Revises: 0825f7a20c85
Create Date: 2020-03-19 18:34:50.717253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd359ff9cd8a'
down_revision = '0825f7a20c85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    op.drop_table('role')
    op.drop_column('Users', 'confirmed_at')
    op.drop_column('Users', 'active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('active', sa.BOOLEAN(), nullable=True))
    op.add_column('Users', sa.Column('confirmed_at', sa.DATETIME(), nullable=True))
    op.create_table('role',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=40), nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('role_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users._id'], )
    )
    # ### end Alembic commands ###
